username: liyang-normal
my:
  username: frank
  est: 2014
  website: ${my.username}.com
  desc: "${my.website} forever rise!"


spring:
  datasource:
    data-password:
    data-username: root
server:
  port: 8080
  context-path: /boot
